name: Dependabot auto-merge
run-name: Merging PR ${{ github.event.workflow_run.pull_requests[0].number }}
on:
  workflow_run:
    branches:
      - dependabot/**
    types:
      - completed
    workflows:
      - "Continuous integration"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v6.0.2
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
            -d '{"state":"pending","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Auto-merge is running","context":"Auto-merge PR"}'
      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"

      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
            -d '{"state":"success","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Auto-merge is completed","context":"Auto-merge PR"}'
